version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: FortyfivePaca4577
      POSTGRES_DB: ETL_Celerix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_HOST=localhost #antes estaba db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=FortyfivePaca4577
      - DB_NAME=ETL_Celerix
    command: ["python", "script.py"]

volumes:
  postgres_data:
